apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pssparams.stackhpc.com
spec:
  group: stackhpc.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            allowedCapabilities:
              items:
                type: string
              type: array
            allowedSysctls:
              items:
                type: string
              type: array
            allowedSelinuxTypes:
              items:
                type: string
              type: array
  scope: Cluster
  names:
    plural: pssparams
    singular: pssparam
    kind: PSSParams
