apiVersion: "policy.stackhpc.com/v1"
kind: PSSParams
metadata:
  name: helm-values
allowedCapabilities:
{{- range $.Values.allowedCapabilities }}
- {{ . }}
{{- end }}
allowedSysctls:
{{- range $.Values.allowedSysctls }}
- {{ . }}
{{- end }}
allowedSelinuxTypes:
{{- range $.Values.allowedSelinuxTypes }}
- {{ . }}
{{- end }}
allowedVolumeTypes:
{{- range $.Values.allowedVolumeTypes }}
- {{ . }}
{{- end }}