{{- range list "containers" "initcontainers" "ephemeralcontainers" "pod" }}
# AppArmor ---------------------------------------------------------------------
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  creationTimestamp: null
  name: apparmor-{{ . }}
spec:
  matchResources:
    namespaceSelector: 
{{ $.Values.defaultBindingNamespaceSelector | toYaml | indent 6 }}
  policyName: not-overriding-apparmor-{{ . }}
  validationActions:
  - Deny
# Run as non-root --------------------------------------------------------------
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  creationTimestamp: null
  name: run-as-non-root-{{ . }}
spec:
  matchResources:
    namespaceSelector: 
{{ $.Values.defaultBindingNamespaceSelector | toYaml | indent 6 }}
  policyName: run-as-non-root-{{ . }}
  validationActions:
  - Deny
# Non-root user --------------------------------------------------------------
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  creationTimestamp: null
  name: non-root-user-{{ . }}
spec:
  matchResources:
    namespaceSelector: 
{{ $.Values.defaultBindingNamespaceSelector | toYaml | indent 6 }}
  policyName: non-root-user-{{ . }}
  validationActions:
  - Deny
# SELinux ---------------------------------------------------------------------
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  creationTimestamp: null
  name: selinux-type-{{ . }}
spec:
  paramRef:
    name: helm-values
    parameterNotFoundAction: Deny
  matchResources:
    namespaceSelector: 
{{ $.Values.defaultBindingNamespaceSelector | toYaml | indent 6 }}
  policyName: selinux-type-{{ . }}
  validationActions:
  - Deny
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  creationTimestamp: null
  name: selinux-users-{{ . }}
spec:
  matchResources:
    namespaceSelector: 
{{ $.Values.defaultBindingNamespaceSelector | toYaml | indent 6 }}
  policyName: selinux-users-{{ . }}
  validationActions:
  - Deny
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  creationTimestamp: null
  name: selinux-roles-{{ . }}
spec:
  matchResources:
    namespaceSelector: 
{{ $.Values.defaultBindingNamespaceSelector | toYaml | indent 6 }}
  policyName: selinux-roles-{{ . }}
  validationActions:
  - Deny
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  creationTimestamp: null
  name: seccomp-{{ . }}
spec:
  matchResources:
    namespaceSelector: 
{{ $.Values.defaultBindingNamespaceSelector | toYaml | indent 6 }}
  policyName: seccomp-{{ . }}
  validationActions:
  - Deny
{{- end }}
