{{- range tuple "containers" "initcontainers" "ephemeralcontainers" }}
# Privileged containers ---------------------------------------------------------
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  creationTimestamp: null
  name: privileged-{{ . }}
spec:
  matchResources:
    namespaceSelector: 
{{ $.Values.defaultBindingNamespaceSelector | toYaml | indent 6 }}
  policyName: kubescape-c-0057-privileged-container-denied-{{ . }}
  validationActions:
  - Deny
# Capabilities ------------------------------------------------------------------
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  creationTimestamp: null
  name: capabilities-{{ . }}
spec:
  matchResources:
    namespaceSelector: 
{{ $.Values.defaultBindingNamespaceSelector | toYaml | indent 6 }}
  paramRef:
    name: helm-values
    parameterNotFoundAction: Deny
  policyName: adding-insecure-capabilities-{{ . }}
  validationActions:
  - Deny
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  creationTimestamp: null
  name: drop-capabilities-{{ . }}
spec:
  matchResources:
    namespaceSelector: 
{{ $.Values.defaultBindingNamespaceSelector | toYaml | indent 6 }}
  paramRef:
    name: helm-values
    parameterNotFoundAction: Deny
  policyName: must-drop-capabilities-{{ . }}
  validationActions:
  - Deny
# Host ports -------------------------------------------------------------------
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  creationTimestamp: null
  name: host-ports-{{ . }}
spec:
  matchResources:
    namespaceSelector: 
{{ $.Values.defaultBindingNamespaceSelector | toYaml | indent 6 }}
  policyName: kubescape-c-0044-deny-resources-with-host-port-{{ . }}
  validationActions:
  - Deny
# Privilege escalation ---------------------------------------------------------
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  creationTimestamp: null
  name: privilege-escalation-{{ . }}
spec:
  matchResources:
    namespaceSelector: 
{{ $.Values.defaultBindingNamespaceSelector | toYaml | indent 6 }}
  policyName: kubescape-c-0016-allow-privilege-escalation-{{ . }}
  validationActions:
  - Deny
{{- end }}