defaultBindingNamespaceSelector:
  matchExpressions:
  - key: kubernetes.io/metadata.name
    operator: In
    values:
    - default

bindingNamespaceSelectorOverrides:
  runAsNonRoot:
  apparmor:
  nonRootUser:
  selinux:
  seccomp:
  privilegedContainers:
  capabilities:
  hostPorts:
  privilegeEscalation:
  procMountType:
  hostNamespaces:
  hostPathVolumes:
  sysctls:
  volumeTypes:

allowedCapabilities:
- NET_BIND_SERVICE

allowedSysctls:
- kernel.shm_rmid_forced
- net.ipv4.ip_local_port_range
- net.ipv4.ip_unprivileged_port_start
- net.ipv4.tcp_syncookies
- net.ipv4.ping_group_range
- net.ipv4.ip_local_reserved_ports
- net.ipv4.tcp_keepalive_time
- net.ipv4.tcp_fin_timeout
- net.ipv4.tcp_keepalive_intvl
- net.ipv4.tcp_keepalive_probes

allowedSelinuxTypes:
- container_t
- container_init_t
- container_kvm_t
- container_engine_t

allowedVolumeTypes:
- configMap
- csi
- downwardAPI
- emptyDir
- ephemeral
- persistentVolumeClaim
- projected
- secret
